# Chave única do projeto (você encontra no painel do SonarCloud)
sonar.projectKey=lucas-gatto
sonar.organization=Lucas Aguena Gatto

# Onde o código-fonte está (geralmente 'src' ou '.')
sonar.sources=backend,ecobalance

